---
deployment:
  tasks:
    # Set deployment path to staging subdomain
    - export DEPLOYPATH=/home2/flairpla/new.flair-plastic.hu/public_html/
    # Copy all files to staging directory
    - /bin/cp -R * $DEPLOYPATH
    # Navigate to staging directory
    - cd $DEPLOYPATH
    # Install production dependencies
    - /opt/cpanel/ea-nodejs20/bin/npm install --production
    # Build the Next.js application
    - /opt/cpanel/ea-nodejs20/bin/npm run build
    # Create tmp directory for Passenger restart
    - mkdir -p tmp
    # Touch restart file to restart the application
    - touch tmp/restart.txt
