import { NextApiRequest, NextApiResponse } from 'next';
import { SEO_CONFIG } from '../../lib/seo/config';

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  const robotsTxt = `# Robots.txt for ${SEO_CONFIG.site.name}
# Generated by Next.js SEO System

User-agent: *
Allow: /

# Crawl delay for all crawlers
Crawl-delay: 1

# Disallow specific paths
Disallow: /api/
Disallow: /admin/
Disallow: /_next/
Disallow: /404
Disallow: /500
Disallow: /*.json$
Disallow: /search?

# Allow common SEO paths
Allow: /api/sitemap.xml
Allow: /api/robots.txt

# Sitemap location
Sitemap: ${SEO_CONFIG.site.domain}/api/sitemap.xml

# Host directive (helps with canonicalization)
Host: ${SEO_CONFIG.site.domain}

# User-agent specific rules
User-agent: Googlebot
Allow: /
Crawl-delay: 1

User-agent: Bingbot
Allow: /
Crawl-delay: 2

User-agent: Slurp
Allow: /
Crawl-delay: 2

# Block AI training bots if desired
User-agent: GPTBot
Disallow: /

User-agent: ChatGPT-User
Disallow: /

User-agent: CCBot
Disallow: /

User-agent: anthropic-ai
Disallow: /

User-agent: Claude-Web
Disallow: /

# Block common spammers and scrapers
User-agent: AhrefsBot
Disallow: /

User-agent: SemrushBot
Disallow: /

User-agent: MJ12bot
Disallow: /

# SEO-friendly robots directives
# Last updated: ${new Date().toISOString()}
`;

  // Set headers for robots.txt
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=86400'); // Cache for 24 hours
  
  res.status(200).send(robotsTxt);
}
