// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckkxncnbtuehsfibvziw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNra3huY25idHVlaHNmaWJ2eml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODAyNjIsImV4cCI6MjA2MDY1NjI2Mn0.76Sr-oJxaoRUpM6d5Kbl2zuYbGQzdg4gWxKWk8jxhS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);